"""Create tables

Revision ID: 547e0602b861
Revises: 
Create Date: 2025-10-08 18:08:15.445903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547e0602b861'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packs',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('card_type', sa.Enum('IRREGULAR_VERB', 'TRANSLATION', name='cardtype'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packs'))
    )
    op.create_table('users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_users_telegram_id'))
    )
    op.create_table('irregular_verb_cards',
    sa.Column('base_form', sa.String(length=30), nullable=False),
    sa.Column('past_simple', sa.String(length=30), nullable=False),
    sa.Column('past_participle', sa.String(length=30), nullable=False),
    sa.Column('translation', sa.String(length=30), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], name=op.f('fk_irregular_verb_cards_pack_id_packs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_irregular_verb_cards'))
    )
    op.create_index(op.f('ix_irregular_verb_cards_pack_id'), 'irregular_verb_cards', ['pack_id'], unique=False)
    op.create_table('translation_cards',
    sa.Column('original', sa.String(length=255), nullable=False),
    sa.Column('translation', sa.String(length=255), nullable=False),
    sa.Column('pack_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pack_id'], ['packs.id'], name=op.f('fk_translation_cards_pack_id_packs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_translation_cards'))
    )
    op.create_index(op.f('ix_translation_cards_pack_id'), 'translation_cards', ['pack_id'], unique=False)
    op.create_table('progresss',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('interval_level', sa.Integer(), nullable=False),
    sa.Column('next_repeat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['translation_cards.id'], name=op.f('fk_progresss_card_id_translation_cards')),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], name=op.f('fk_progresss_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'card_id', name=op.f('pk_progresss'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresss')
    op.drop_index(op.f('ix_translation_cards_pack_id'), table_name='translation_cards')
    op.drop_table('translation_cards')
    op.drop_index(op.f('ix_irregular_verb_cards_pack_id'), table_name='irregular_verb_cards')
    op.drop_table('irregular_verb_cards')
    op.drop_table('users')
    op.drop_table('packs')
    # ### end Alembic commands ###
